name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v2
#       with:
#         registry: ghcr.io
#         username: ${{ github.repository_owner }}
#         password: ${{ secrets.GITHUB_TOKEN }}
# repo ghcr.io/
    - name: Build and push controller
      uses: docker/build-push-action@v3
      with:
        context: hairpin-proxy-controller
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          uomumeraltaf/hairpin-proxy-controller:latest
          uomumeraltaf/hairpin-proxy-controller:0.4.0
    - name: Build and push proxy
      uses: docker/build-push-action@v3
      with:
        context: hairpin-proxy-haproxy
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          uomumeraltaf/hairpin-proxy-haproxy:latest
          uomumeraltaf/hairpin-proxy-haproxy:0.4.0
